package com.maomao2.databasesharding.mapper.pkg1;

import com.maomao2.databasesharding.model.HiveTable;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiveTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    @Delete({
        "delete from hivetable",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    @Insert({
        "insert into hivetable (id, dbName, ",
        "tableName, location, ",
        "createTime, updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{dbname,jdbcType=VARCHAR}, ",
        "#{tablename,jdbcType=VARCHAR}, #{location,jdbcType=VARCHAR}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(HiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    int insertSelective(HiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, dbName, tableName, location, createTime, updateTime",
        "from hivetable",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.maomao2.databasesharding.mapper.pkg1.HiveTableMapper.BaseResultMap")
    HiveTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    @Update({
        "update hivetable",
        "set dbName = #{dbname,jdbcType=VARCHAR},",
          "tableName = #{tablename,jdbcType=VARCHAR},",
          "location = #{location,jdbcType=VARCHAR},",
          "createTime = #{createtime,jdbcType=TIMESTAMP},",
          "updateTime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HiveTable record);
}