package com.maomao2.databasesharding.mapper.pkg1;

import com.maomao2.databasesharding.model.HiveLocation;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiveLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    @Delete({
        "delete from hivelocation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    @Insert({
        "insert into hivelocation (id, location, ",
        "size, createTime, ",
        "updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{location,jdbcType=VARCHAR}, ",
        "#{size,jdbcType=INTEGER}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(HiveLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    int insertSelective(HiveLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, location, size, createTime, updateTime",
        "from hivelocation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.maomao2.databasesharding.mapper.pkg1.HiveLocationMapper.BaseResultMap")
    HiveLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HiveLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    @Update({
        "update hivelocation",
        "set location = #{location,jdbcType=VARCHAR},",
          "size = #{size,jdbcType=INTEGER},",
          "createTime = #{createtime,jdbcType=TIMESTAMP},",
          "updateTime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HiveLocation record);
}