package com.maomao2.databasesharding.model;

import java.util.Date;

public class HiveTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivetable.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivetable.dbName
     *
     * @mbg.generated
     */
    private String dbname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivetable.tableName
     *
     * @mbg.generated
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivetable.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivetable.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivetable.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivetable
     *
     * @mbg.generated
     */
    public HiveTable(Integer id, String dbname, String tablename, String location, Date createtime, Date updatetime) {
        this.id = id;
        this.dbname = dbname;
        this.tablename = tablename;
        this.location = location;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivetable.id
     *
     * @return the value of hivetable.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivetable.dbName
     *
     * @return the value of hivetable.dbName
     *
     * @mbg.generated
     */
    public String getDbname() {
        return dbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivetable.tableName
     *
     * @return the value of hivetable.tableName
     *
     * @mbg.generated
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivetable.location
     *
     * @return the value of hivetable.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivetable.createTime
     *
     * @return the value of hivetable.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivetable.updateTime
     *
     * @return the value of hivetable.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }
}