package com.maomao2.databasesharding.model;

import java.util.Date;

public class HiveLocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivelocation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivelocation.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivelocation.size
     *
     * @mbg.generated
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivelocation.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hivelocation.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    public HiveLocation(){

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hivelocation
     *
     * @mbg.generated
     */
    public HiveLocation(Integer id, String location, Integer size, Date createtime, Date updatetime) {
        this.id = id;
        this.location = location;
        this.size = size;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivelocation.id
     *
     * @return the value of hivelocation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivelocation.location
     *
     * @return the value of hivelocation.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivelocation.size
     *
     * @return the value of hivelocation.size
     *
     * @mbg.generated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivelocation.createTime
     *
     * @return the value of hivelocation.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hivelocation.updateTime
     *
     * @return the value of hivelocation.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }
}